def cities_to_use():
    return ['amsterdam', 
            'antwerp', 
            'asheville', 
            'athens', 
            'austin', 
            'bangkok', 
            'barcelona', 
            'barossa valley',
            'barwon south west', 
            'beijing', 
            'belize', 
            'bergamo', 
            'berlin', 
            'bologna', 
            'bordeaux', 
            'boston', 
            'bristol', 
            'broward county', 
            'brussels', 
            'buenos aires', 
            'cambridge MA', 
            'cape town',
            'chicago',
            'sevilla', 
            'shanghai']

def columns_to_use():
    return ['host_id', 
            'host_response_rate', 
            'host_acceptance_rate', 
            'latitude', 
            'longitude', 
            'accommodates', 
            'price', 
            'number_of_reviews', 
            'reviews_per_month', 
            'neighbourhood_cleansed',
            'host_response_time', 
            'host_is_superhost', 
            'host_total_listings_count', 
            'host_has_profile_pic',
            'host_identity_verified', 
            'neighbourhood', 
            'property_type',
            'room_type', 
            'bathrooms', 
            'bedrooms', 
            'beds']

def columns_to_fit():
    return ['host_id', 
            'host_response_rate', 
            'host_acceptance_rate', 
            'northing', 
            'easting', 
            'accommodates', 
            'number_of_reviews', 
            'reviews_per_month', 
            'neighbourhood_cleansed',
            'host_response_time', 
            'host_is_superhost', 
            'host_total_listings_count', 
            'host_has_profile_pic',
            'host_identity_verified', 
            'neighbourhood', 
            'property_type',
            'room_type', 
            'bathrooms', 
            'bedrooms', 
            'beds']
